on: push

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        b:
          - b-commonjs
          - b-es2015
          - b-typescript
    steps:
      - uses: actions/checkout@v2
      - run: |
          pushd a
          yarn
          yarn build
          popd
          cd ${{ matrix.b }}
          yarn
          yarn build || true
          yarn test
